alias be='bundle exec'
alias brake='bundle exec rake'
alias bi='bundle install'

alias fserver="ruby -rwebrick -e'WEBrick::HTTPServer.new(:Port => 8000, :DocumentRoot => Dir.pwd).start'"

alias vg='vagrant'
alias d='docker'
alias dsall="docker ps | awk '{ print $1 }' | tail -n +2 | xargs docker stop"
alias diclean="docker images | grep '<none>' | awk '{ print $3 }' | xargs docker rmi -f"
alias compose='docker-compose'
alias k='kubectl'
alias pd='pdata'

alias pgrep='ps aux | grep $1'
alias jsonpp='python -mjson.tool'

alias gpall='for i in $(ls); do (cd $i && [[ -d .git ]] && echo "Pulling changes for $i branch: $(git rev-parse --abbrev-ref HEAD)" && git pull -r); done'
